default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: b_blog_development

test:
  <<: *default
  database: b_blog_test

production:
  <<: *default
  database: b_blog_production
  username: b_blog
  password: <%= ENV["B_BLOG_DATABASE_PASSWORD"] %>
