test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true
  
digitalocean:
  service: S3
  access_key_id: "<%= ENV['DIGITALOCEAN_KEY'] %>"
  secret_access_key: "<%= ENV['DIGITALOCEAN_SECRET'] %>"
  endpoint: "<%= ENV['DIGITALOCEAN_ENDPOINT'] %>"
  region: "<%= ENV['DIGITALOCEAN_REGION'] %>"
  bucket: "<%= ENV['DIGITALOCEAN_BUCKET'] %>"
  public: true